name: Pipeline-Frontend
on:
  push:
    branches:
      - master
  
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Tag
        id: set_tag
        run: |
          fullTag=${{ github.ref }}
          tag=${fullTag#refs/tags/}
          echo "tag=${tag}" >> $GITHUB_OUTPUT 
        #  script: |
        #  - echo "tag=${{ github.ref }}"
        #  - sed 's/^refs\/tags\///' >> $GITHUB_OUTPUT
        #run: echo "tag=${{ github.ref }}" >> $GITHUB_ENV
        #run: echo "tag=${{ github.ref | removeprefix refs/tags/ }}" >> $GITHUB_OUTPUT
        #run: echo "tag=${{ github.ref | replace \"refs/tags/\", \"\" }}" >> $GITHUB_OUTPUT
        #run: echo "tag=${{ github.ref }}" | sed 's/^refs\/tags\///' >> $GITHUB_OUTPUT
        #run: echo "tag=${{ github.ref }}" | awk -F '/' '{print $2}' >> $GITHUB_OUTPUT
        # run:
        #   - echo "tag=${{ github.ref }}"
        #   - sed 's/^refs\/tags\///' >> $GITHUB_OUTPUT
      
      - name: Build Frontend Docker image
        run: docker build -t nacromancer858/frontend-image-7:${{ steps.set_tag.outputs.tag }} .
        working-directory: ./frontend
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
       
      - name: Push Frontend Docker image
        run: docker push nacromancer858/frontend-image-7:${{ steps.set_tag.outputs.tag }}
        working-directory: ./frontend
       
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop frontend_container
            sudo docker rm frontend_container
            sudo docker pull nacromancer858/frontend-image-7:${{ steps.set_tag.outputs.tag }}
            sudo docker run -d --name frontend_container --network simple-crud-react-nodejs_frontend_network nacromancer858/frontend-image-7:${{ steps.set_tag.outputs.tag }}
            


     

