# name: Pipeline-Frontend 
# on:
#   push:
#     branches:
#       - master
#     tags:
#       - '*'
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: "Release tag for backend docker image"
#         required: true
#                                                   #   push:
#                                                   #     tags:
#                                                   #       - '*'
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
        
#       - name: debug
#         run: echo ${{ github.ref }}
#       - name: Build Frontend Docker image
#         run: |
#           docker build -t nacromancer858/frontend-image-777:${{ github.event.inputs.tag }} .
#         working-directory: ./frontend
        
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
       
#       - name: Push Frontend Docker image
#         run: docker push nacromancer858/frontend-image-777:${{ github.event.inputs.tag }}
#         working-directory: ./frontend
       
#       - name: Deploy to EC2 instance
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.USER_NAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#            sudo docker rmi -f frontend_container
#            sudo docker pull nacromancer858/frontend-image-777:${{ github.event.inputs.tag }}
#            sudo docker run -d -p 80:80 --name frontend_container nacromancer858/frontend-image-777:${{ github.event.inputs.tag }}
